# Generated by Django 2.2.6 on 2019-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qd', '0003_remove_qd_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qd',
            name='create_time',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
