# Generated by Django 2.2.6 on 2019-11-06 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clazz.Clazz'),
        ),
    ]
