# Generated by Django 2.2.6 on 2019-11-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191106_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cid',
            new_name='clazz',
        ),
    ]
