# Generated by Django 2.2.6 on 2019-11-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191106_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rid',
            field=models.IntegerField(default=1),
        ),
    ]
